# Generated by Django 3.2.8 on 2021-10-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=255, null=True)),
                ('xray', models.ImageField(blank=True, upload_to='original/')),
                ('prediction_img', models.ImageField(blank=True, upload_to='prediction/')),
                ('covid_percentage', models.FloatField(blank=True, null=True)),
                ('pneumonia_percentage', models.FloatField(blank=True, null=True)),
                ('prediction', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
