# Generated by Django 3.2.8 on 2022-01-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='normal_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
