name: Testing
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  django_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run django tests
      run: |
        pip3 install -r requirements.txt
        python3 manage.py test
