name: Testing
on: push

jobs:
  django_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run django urls test
      run: |
        pip3 install -r requirements.txt
        python3 manage.py test
